title: datahazard
description: > # this means to ignore newlines until "baseurl:"
  Blog about Python and JavaScript.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://datahazard.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Oskaras Kanasevicius # add your name
author-img: oskaras.jpg # add your photo
about-author: Python and JavaScript Developer  # add description
social-twitter: oskkana # add your Twitter handle
social-facebook: oskaras.kan # add your Facebook handle
social-github: datahazard # add your Github handle
social-linkedin: oskaraskanasevicius # add your Linkedin handle
social-email: oskaraskanasevicius@outlook.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
